// import axios from 'axios'

export default {
  fetchMovieCollection: (name) => {
    return { 'Search': [{ 'Title': 'Indiana Jones and the Last Crusade', 'Year': '1989', 'imdbID': 'tt0097576', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg' }, { 'Title': 'Indiana Jones and the Temple of Doom', 'Year': '1984', 'imdbID': 'tt0087469', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMGI1NTk2ZWMtMmI0YS00Yzg0LTljMzgtZTg4YjkyY2E5Zjc0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg' }, { 'Title': 'Indiana Jones and the Kingdom of the Crystal Skull', 'Year': '2008', 'imdbID': 'tt0367882', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZDIzNzM5MDUtZmI5MC00NGQ5LWFlNzEtYzE3ODIxNDI3ZmNhXkEyXkFqcGdeQXVyNjQ4ODE4MzQ@._V1_SX300.jpg' }, { 'Title': 'Indiana Jones and the Temple of the Forbidden Eye Ride', 'Year': '1995', 'imdbID': 'tt0764648', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMzk5ZmEyMTgtYzQ0ZC00YTEwLWExOTUtMDZhZmY5NDQ0OGJlXkEyXkFqcGdeQXVyNzAyNzI4Njc@._V1_SX300.jpg' }, { 'Title': 'The Adventures of Young Indiana Jones: Treasure of the Peacocks Eye', 'Year': '1995', 'imdbID': 'tt0115031', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BOTg2MTc2NDAzOF5BMl5BanBnXkFtZTcwODExNDIyMQ@@._V1_SX300.jpg' }, { 'Title': 'The Adventures of Young Indiana Jones: Travels with Father', 'Year': '1996', 'imdbID': 'tt0154003', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMjU0NTY3M2UtZGJlYi00MDk4LWE0ZTAtZWI1MzcyZDg3Y2U5XkEyXkFqcGdeQXVyMzU0NzkwMDg@._V1_SX300.jpg' }, { 'Title': 'Mr. Plinketts Indiana Jones and the Kingdom of the Crystal Skull Review', 'Year': '2011', 'imdbID': 'tt6330122', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BNGM4NDA3YTMtMWRiMy00MDgxLTkzMWItMDVjN2EzZmUwYjkxL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTM3NzQ5NzQ@._V1_SX300.jpg' }, { 'Title': 'The Adventures of Young Indiana Jones: Attack of the Hawkmen', 'Year': '1995', 'imdbID': 'tt0154004', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTcwMTU5NjExMV5BMl5BanBnXkFtZTYwNzU3MTA5._V1_SX300.jpg' }, { 'Title': 'Monrovia, Indiana', 'Year': '2018', 'imdbID': 'tt8749146', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMTU0MTQ0NTI2Ml5BMl5BanBnXkFtZTgwNjAzMjE1NjM@._V1_SX300.jpg' }, { 'Title': 'The Adventures of Young Indiana Jones: Daredevils of the Desert', 'Year': '1999', 'imdbID': 'tt0275186', 'Type': 'movie', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZDQ0NGI4ZjktYmQyNC00ZDZhLTgyMGYtYjU1Zjg5N2YzZDRlXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg' }], 'totalResults': '160', 'Response': 'True' }
  },

  fetchSingleMovie: (id) => {
    return { 'Title': 'The Adventures of Young Indiana Jones: Treasure of the Peacocks Eye', 'Year': '1995', 'Rated': 'N/A', 'Released': '16 Jan 1995', 'Runtime': '94 min', 'Genre': 'Action, Adventure', 'Director': 'Carl Schultz', 'Writer': 'Jule Selbo', 'Actors': 'Sean Patrick Flanery, Ronny Coutteure, Adrian Edmondson, Jayne Ashbourne', 'Plot': 'Henry \'Indiana\' Jones, Jr. (Sean Patrick Flanery) is on the trail of a 140-carat diamond that once belonged to Alexander the Great, using a map given to him by a dying soldier.', 'Language': 'English', 'Country': 'USA', 'Awards': 'N/A', 'Poster': 'https://m.media-amazon.com/images/M/MV5BOTg2MTc2NDAzOF5BMl5BanBnXkFtZTcwODExNDIyMQ@@._V1_SX300.jpg', 'Ratings': [{ 'Source': 'Internet Movie Database', 'Value': '6.7/10' }], 'Metascore': 'N/A', 'imdbRating': '6.7', 'imdbVotes': '866', 'imdbID': 'tt0115031', 'Type': 'movie', 'DVD': '26 Oct 1999', 'BoxOffice': 'N/A', 'Production': 'N/A', 'Website': 'N/A', 'Response': 'True' }
  }
}
